[package]
name = "ui_components"
version = "0.0.0"
edition = "2021"
[lints]
workspace = true


[lib]
test = false
doctest = false
bench = false

[dependencies]
action_data = { path = "../action_data" }
asset_paths = { path = "../asset_paths" }
core_data = { path = "../core_data" }
masonry = { path = "../masonry" }

bon = "3"
schemars = "0.8"
serde = { version = "1", features = ["derive"] }
