[package]
name = "ui_components"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
action_data_old = { path = "../action_data_old" }
asset_paths = { path = "../asset_paths" }
core_data = { path = "../core_data" }
masonry = { path = "../masonry" }

bon = "3"
