[package]
name = "battle_queries"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
ability_data = { path = "../ability_data" }
action_data = { path = "../action_data" }
assert_with = { path = "../assert_with" }
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }

bit-set = "0.8"
tracing = "0.1"