[package]
name = "battle_queries"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
ability_data = { path = "../ability_data" }
action_data = { path = "../action_data" }
battle_data = { path = "../battle_data" }
core_data = { path = "../core_data" }

tracing = "0.1"