[package]
name = "engine"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
core_data = { path = "../core_data" }
display_data = { path = "../display_data" }

uuid = { version = "1", features = ["serde", "v4"] }