[package]
name = "display_old"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
action_data_old = { path = "../action_data_old" }
ai_data = { path = "../ai_data" }
assert_with = { path = "../assert_with" }
battle_data_old = { path = "../battle_data_old" }
battle_queries_old = { path = "../battle_queries_old" }
core_data = { path = "../core_data" }
display_data_old = { path = "../display_data_old" }
masonry = { path = "../masonry" }
ui_components = { path = "../ui_components" }

bon = "3"