[package]
name = "ability_data"
version = "0.0.0"
edition = "2021"
[lints]
workspace = true


[lib]
test = false
doctest = false
bench = false

[dependencies]
core_data = { path = "../core_data" }

schemars = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }