#!/usr/bin/env bash
set -euo pipefail

DIR="client/Assets/StreamingAssets/Tabula.xlsm.d"
XLSM="client/Assets/StreamingAssets/Tabula.xlsm"

if [[ -d "$DIR" ]]; then
  if [[ ! -f "$XLSM" ]] || [[ "$DIR" -nt "$XLSM" ]]; then
    python3 client/scripts/xlsm_pack.py "$DIR" "$XLSM" --overwrite
  fi
fi

