#!/bin/bash

cd "$(git rev-parse --show-toplevel)" || exit 1

just fods

if [ $? -ne 0 ]; then
    echo "Error: 'just fods' failed. Commit aborted."
    exit 1
fi

git add client/Assets/StreamingAssets/Tabula.fods

exit 0
