[package]
name = "database"
version = "0.0.0"
edition = "2024"
[lints]
workspace = true


[lib]
test = false
doctest = false
bench = false

[dependencies]
ai_data = { path = "../ai_data" }
action_data = { path = "../action_data" }
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }
game_creation = { path = "../game_creation" }

rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }