[package]
name = "database"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
ai_data = { path = "../ai_data" }
action_data = { path = "../action_data" }
battle_data_old = { path = "../battle_data_old" }
core_data = { path = "../core_data" }
quest_data = { path = "../quest_data" }

rusqlite = { version = "0.35", features = ["serde_json", "bundled", "uuid"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }