[package]
name = "masonry"
version = "0.0.0"
edition = "2024"
[lints]
workspace = true


[lib]
test = false
doctest = false
bench = false

[dependencies]
action_data = { path = "../action_data" }
core_data = { path = "../core_data" }

bon = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
