[package]
name = "parser_cli"
version = "0.0.0"
edition = "2021"
[lints]
workspace = true


[[bin]]
name = "parser_cli"
test = false
doctest = false
bench = false

[dependencies]
parser = { path = "../parser" }

ariadne = "0.2"
clap = { version = "4.5", features = ["derive"] }
ron = "0.8"