[package]
name = "parser_cli"
version = "0.0.0"
edition = "2024"
[lints]
workspace = true


[[bin]]
name = "parser_cli"
test = false
doctest = false
bench = false

[dependencies]
parser = { path = "../parser" }

ariadne = { workspace = true }
clap = { workspace = true }
ron = { workspace = true }