[package]
name = "ability_data"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
core_data = { path = "../core_data" }

serde = { version = "1", features = ["derive"] }