[package]
name = "ai_monte_carlo"
version = "0.0.0"
description = "Random search AI algorithms"
license = "Apache-2.0"
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
ai_core = { path = "../ai_core", version = "0.0.0" }

petgraph = "0.6"
rand = "0.9"
tracing = "0.1"