[package]
name = "logging"
version = "0.0.0"
edition = "2024"
[lints]
workspace = true


[lib]
path = "src/logging.rs"
test = false
doctest = false
bench = false

[dependencies]
battle_state = { path = "../battle_state" }

serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-forest = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
