[package]
name = "logging"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/logging.rs"
test = false
doctest = false
bench = false

[dependencies]
tracing = "0.1"
tracing-error = "0.2"
tracing-forest = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }