[package]
name = "logging"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/logging.rs"
doctest = false
bench = false

[dependencies]
display_data = { path = "../display_data" }
battle_data = { path = "../battle_data" }
core_data = { path = "../core_data" }

rand_xoshiro = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-error = "0.2"
tracing-forest = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }
