use battle_state::actions::battle_actions::BattleAction;
use battle_state::battle::battle_state::BattleState;
use core_data::types::PlayerName;

use crate::uct_config::UctConfig;
use crate::uct_search;

/// Monte Carlo search with heuristic position assignments.
///
/// Replaces the multi-step positioning flow with atomic position
/// assignments generated by a heuristic and evaluated as root-level
/// MCTS actions.
pub fn search(
    initial_battle: &BattleState,
    player: PlayerName,
    config: &UctConfig,
) -> BattleAction {
    uct_search::search(initial_battle, player, config)
}
