[package]
name = "ai_data"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
core_data = { path = "../core_data" }

schemars = "0.8"
serde = { version = "1", features = ["derive"] }
