//! This file is generated by `tabula generate`. Do not edit manually.

use core_data::identifiers::{BaseCardId, DreamwellCardId};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use uuid::uuid;

pub const TEST_DREAMWELL_NO_ABILITIES: &[DreamwellCardId] = &[
    DreamwellCardId(uuid!("308fd4c0-ca98-4bfa-a9be-c29b36a145fd")),
    DreamwellCardId(uuid!("308fd4c0-ca98-4bfa-a9be-c29b36a145fd")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
    DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2")),
];

pub const TEST_DREAMWELL_BASIC_5: &[DreamwellCardId] = &[
    DreamwellCardId(uuid!("308fd4c0-ca98-4bfa-a9be-c29b36a145fd")),
    DreamwellCardId(uuid!("308fd4c0-ca98-4bfa-a9be-c29b36a145fd")),
    DreamwellCardId(uuid!("40c77ea8-a021-4bc6-8970-0853c03f3fe0")),
    DreamwellCardId(uuid!("d386663c-9e9f-4b8e-b410-f3467e39801b")),
    DreamwellCardId(uuid!("107c3b3f-6131-4ff8-afcb-f0ce4188848f")),
    DreamwellCardId(uuid!("40e4381f-12f7-46b9-ae50-67b3195781b1")),
    DreamwellCardId(uuid!("a2cdf115-8e1a-455e-a118-123f6f36c7ba")),
];

pub const DREAMWELL_BASIC_5: &[DreamwellCardId] = &[
    DreamwellCardId(uuid!("bc143c3c-f149-4506-813f-1aa8dd54e370")),
    DreamwellCardId(uuid!("1dda2551-c972-4db2-81c0-9dc95ac8b27c")),
    DreamwellCardId(uuid!("dcd99f3d-8c47-47fa-9b9a-4c1455a9d2eb")),
    DreamwellCardId(uuid!("276c1e23-53d8-4aeb-a4dd-243189a44561")),
    DreamwellCardId(uuid!("63d5d9f5-208f-4e35-9681-d51a5ba6ce57")),
    DreamwellCardId(uuid!("8e5b3423-b8e1-4e1c-9e3e-5281190c4713")),
    DreamwellCardId(uuid!("e2c10a87-e92f-4170-9bbf-c288abcf9f9b")),
];

pub const CORE_11: &[BaseCardId] = &[
    BaseCardId(uuid!("36c2a4e1-3212-4933-979a-73f109f9b256")),
    BaseCardId(uuid!("36c2a4e1-3212-4933-979a-73f109f9b256")),
    BaseCardId(uuid!("36c2a4e1-3212-4933-979a-73f109f9b256")),
    BaseCardId(uuid!("36c2a4e1-3212-4933-979a-73f109f9b256")),
    BaseCardId(uuid!("36c2a4e1-3212-4933-979a-73f109f9b256")),
    BaseCardId(uuid!("36c2a4e1-3212-4933-979a-73f109f9b256")),
    BaseCardId(uuid!("36c2a4e1-3212-4933-979a-73f109f9b256")),
    BaseCardId(uuid!("36c2a4e1-3212-4933-979a-73f109f9b256")),
    BaseCardId(uuid!("eb85b69a-3771-4148-83cf-a7ddb0caee98")),
    BaseCardId(uuid!("eb85b69a-3771-4148-83cf-a7ddb0caee98")),
    BaseCardId(uuid!("eb85b69a-3771-4148-83cf-a7ddb0caee98")),
    BaseCardId(uuid!("eb85b69a-3771-4148-83cf-a7ddb0caee98")),
    BaseCardId(uuid!("eb85b69a-3771-4148-83cf-a7ddb0caee98")),
    BaseCardId(uuid!("eb85b69a-3771-4148-83cf-a7ddb0caee98")),
    BaseCardId(uuid!("9c605a08-dac4-4c3e-8aff-437b79809937")),
    BaseCardId(uuid!("9c605a08-dac4-4c3e-8aff-437b79809937")),
    BaseCardId(uuid!("9c605a08-dac4-4c3e-8aff-437b79809937")),
    BaseCardId(uuid!("9c605a08-dac4-4c3e-8aff-437b79809937")),
    BaseCardId(uuid!("a6e8e100-9aa6-4a53-82ec-4ab161829533")),
    BaseCardId(uuid!("a6e8e100-9aa6-4a53-82ec-4ab161829533")),
    BaseCardId(uuid!("a6e8e100-9aa6-4a53-82ec-4ab161829533")),
    BaseCardId(uuid!("a6e8e100-9aa6-4a53-82ec-4ab161829533")),
    BaseCardId(uuid!("a6e8e100-9aa6-4a53-82ec-4ab161829533")),
    BaseCardId(uuid!("a6e8e100-9aa6-4a53-82ec-4ab161829533")),
    BaseCardId(uuid!("04be5c1e-20ab-475e-b02f-e78b82ca2e8d")),
    BaseCardId(uuid!("04be5c1e-20ab-475e-b02f-e78b82ca2e8d")),
    BaseCardId(uuid!("04be5c1e-20ab-475e-b02f-e78b82ca2e8d")),
    BaseCardId(uuid!("04be5c1e-20ab-475e-b02f-e78b82ca2e8d")),
    BaseCardId(uuid!("04be5c1e-20ab-475e-b02f-e78b82ca2e8d")),
    BaseCardId(uuid!("04be5c1e-20ab-475e-b02f-e78b82ca2e8d")),
    BaseCardId(uuid!("04be5c1e-20ab-475e-b02f-e78b82ca2e8d")),
    BaseCardId(uuid!("04be5c1e-20ab-475e-b02f-e78b82ca2e8d")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("7285732f-7460-4544-8c74-9300a078a337")),
    BaseCardId(uuid!("1ce137cb-4234-45f7-abd2-d0ce97549885")),
    BaseCardId(uuid!("1ce137cb-4234-45f7-abd2-d0ce97549885")),
    BaseCardId(uuid!("1ce137cb-4234-45f7-abd2-d0ce97549885")),
    BaseCardId(uuid!("1ce137cb-4234-45f7-abd2-d0ce97549885")),
    BaseCardId(uuid!("6e94b4a6-4164-4572-91c1-e74de3e75188")),
    BaseCardId(uuid!("6e94b4a6-4164-4572-91c1-e74de3e75188")),
    BaseCardId(uuid!("6e94b4a6-4164-4572-91c1-e74de3e75188")),
    BaseCardId(uuid!("6e94b4a6-4164-4572-91c1-e74de3e75188")),
    BaseCardId(uuid!("89084e83-a934-4fda-9178-f6a371ccac13")),
    BaseCardId(uuid!("89084e83-a934-4fda-9178-f6a371ccac13")),
    BaseCardId(uuid!("89084e83-a934-4fda-9178-f6a371ccac13")),
    BaseCardId(uuid!("62bf2eb8-4afb-42b1-a8c5-5423eed96545")),
    BaseCardId(uuid!("62bf2eb8-4afb-42b1-a8c5-5423eed96545")),
    BaseCardId(uuid!("62bf2eb8-4afb-42b1-a8c5-5423eed96545")),
    BaseCardId(uuid!("62bf2eb8-4afb-42b1-a8c5-5423eed96545")),
    BaseCardId(uuid!("62bf2eb8-4afb-42b1-a8c5-5423eed96545")),
    BaseCardId(uuid!("62bf2eb8-4afb-42b1-a8c5-5423eed96545")),
    BaseCardId(uuid!("716aa6ec-ddac-488c-aafe-e9a997335c58")),
    BaseCardId(uuid!("716aa6ec-ddac-488c-aafe-e9a997335c58")),
    BaseCardId(uuid!("716aa6ec-ddac-488c-aafe-e9a997335c58")),
    BaseCardId(uuid!("716aa6ec-ddac-488c-aafe-e9a997335c58")),
];

/// Identifies a predefined list of dreamwell_card_id cards.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub enum DreamwellCardIdList {
    TestDreamwellNoAbilities,
    TestDreamwellBasic5,
    DreamwellBasic5,
}

/// Identifies a predefined list of base_card_id cards.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub enum BaseCardIdList {
    Core11,
}

/// Returns the card IDs for the given dreamwell_card_id list.
pub fn dreamwell_card_id_list(list: DreamwellCardIdList) -> &'static [DreamwellCardId] {
    match list {
        DreamwellCardIdList::TestDreamwellNoAbilities => TEST_DREAMWELL_NO_ABILITIES,
        DreamwellCardIdList::TestDreamwellBasic5 => TEST_DREAMWELL_BASIC_5,
        DreamwellCardIdList::DreamwellBasic5 => DREAMWELL_BASIC_5,
    }
}

/// Returns the card IDs for the given base_card_id list.
pub fn base_card_id_list(list: BaseCardIdList) -> &'static [BaseCardId] {
    match list {
        BaseCardIdList::Core11 => CORE_11,
    }
}
