//! This file is generated by `tabula generate`. Do not edit manually.

use core_data::identifiers::{BaseCardId, DreamwellCardId};
use uuid::uuid;

pub const TEST_VANILLA_CHARACTER: BaseCardId = BaseCardId(uuid!("253ee0ca-f973-4d9f-ad37-abe548bc674f"));
/// {Dissolve} an enemy character.
pub const TEST_DISSOLVE: BaseCardId = BaseCardId(uuid!("d4854b6e-5274-4f6a-8a60-a1ea1c15e9a6"));
/// {Prevent} a played card.
pub const TEST_COUNTERSPELL: BaseCardId = BaseCardId(uuid!("aad836b0-3ece-477c-b923-b099360f0115"));
/// {Prevent} a played event unless the opponent pays {energy(e)}.
pub const TEST_COUNTERSPELL_UNLESS_PAYS: BaseCardId = BaseCardId(uuid!("76b6d00c-5a28-4ee3-9655-e4fea1d8a4d8"));
/// Pay 1 or more {energy_symbol}: Draw {cards(cards)} for each {energy_symbol} spent.
pub const TEST_VARIABLE_ENERGY_DRAW: BaseCardId = BaseCardId(uuid!("e06a8cfe-483f-42c0-aac8-9c12b21b3f99"));
/// When you play a card during the opponent's turn, this character gains +{s} spark.
pub const TEST_TRIGGER_GAIN_SPARK_ON_PLAY_CARD_ENEMY_TURN: BaseCardId = BaseCardId(uuid!("86ee5ad7-b60b-4596-af8c-7a495022ac61"));
/// {fast} {energy(e)}: Draw {cards(cards)}.
pub const TEST_FAST_MULTI_ACTIVATED_ABILITY_DRAW_CARD_CHARACTER: BaseCardId = BaseCardId(uuid!("d8a8541f-5b00-4d91-9518-aa8ae70ea450"));
/// Return {up_to_n_events(number)} from your void to your hand.
pub const TEST_RETURN_ONE_OR_TWO_VOID_EVENT_CARDS_TO_HAND: BaseCardId = BaseCardId(uuid!("559e62a0-7ead-4136-8bd4-6cc58db4bef7"));
/// {choose_one} {bullet} {energy(mode1_cost)}: Return an enemy character to hand. {bullet} {energy(mode2_cost)}: Draw {cards(cards)}.
pub const TEST_MODAL_RETURN_TO_HAND_OR_DRAW_TWO: BaseCardId = BaseCardId(uuid!("e8f937da-cca7-447d-a559-530d7c339325"));
/// {Prevent} a played event which could {dissolve} an ally.
pub const TEST_PREVENT_EVENT_WHICH_COULD_DISSOLVE_ALLY: BaseCardId = BaseCardId(uuid!("a9f3e4c7-2b1d-4e8a-9c3f-5d7b8e2a1c4d"));
/// {Foresee(foresee)}. Draw {cards(cards)}.  {ReclaimForCost(reclaim)}
pub const TEST_FORESEE_ONE_DRAW_RECLAIM: BaseCardId = BaseCardId(uuid!("de21db6c-54b4-4bff-b1d6-5a4711ef5ed8"));
/// {Prevent} a played character.
pub const TEST_COUNTERSPELL_CHARACTER: BaseCardId = BaseCardId(uuid!("86ed0d3f-320b-49d0-b022-cd94aa07edbd"));
/// {Dissolve} an enemy character.
pub const TEST_NAMED_DISSOLVE: BaseCardId = BaseCardId(uuid!("3c1dbdc7-702e-4748-af3c-4fd837bcb404"));
/// Draw {cards(cards)}.
pub const TEST_DRAW_ONE: BaseCardId = BaseCardId(uuid!("68f90d08-9b51-424e-90d1-d15ddd1ece93"));
/// When you {materialize} an ally, this character gains +{s} spark.
pub const TEST_TRIGGER_GAIN_SPARK_WHEN_MATERIALIZE_ANOTHER_CHARACTER: BaseCardId = BaseCardId(uuid!("91c9ed93-5faf-4178-aec9-d631bbcf5d6a"));
/// When you play a card during the opponent's turn, this character gains +{s} spark.
pub const TEST_TRIGGER_GAIN_TWO_SPARK_ON_PLAY_CARD_ENEMY_TURN: BaseCardId = BaseCardId(uuid!("82759c0b-5161-4f6f-91b3-d42c2b4e0f9f"));
/// {energy(e)}, once per turn: Draw {cards(cards)}.
pub const TEST_ACTIVATED_ABILITY_DRAW_CARD: BaseCardId = BaseCardId(uuid!("8dfeb2c1-2d72-411c-a8cc-7f84ca532c63"));
/// {energy(e)}: Draw {cards(cards)}.
pub const TEST_MULTI_ACTIVATED_ABILITY_DRAW_CARD_CHARACTER: BaseCardId = BaseCardId(uuid!("56f944bb-333b-4e2c-9c8c-2068f41998c2"));
/// {fast} {energy(e)}, once per turn: Draw {cards(cards)}.
pub const TEST_FAST_ACTIVATED_ABILITY_DRAW_CARD_CHARACTER: BaseCardId = BaseCardId(uuid!("44aa4a1a-e8c6-4969-94bc-5fdbe010395e"));
/// {energy(e)}: {Dissolve} an enemy character.
pub const TEST_ACTIVATED_ABILITY_DISSOLVE_CHARACTER: BaseCardId = BaseCardId(uuid!("785e0341-fdd8-4e05-acb4-cbceed70ea6c"));
/// {energy(e1)}: Draw {cards(cards1)}.  {energy(e2)}: Draw {cards(cards2)}.
pub const TEST_DUAL_ACTIVATED_ABILITY_CHARACTER: BaseCardId = BaseCardId(uuid!("3af84464-874a-4fd2-89cb-1986dee59ae1"));
/// {Foresee(foresee)}.
pub const TEST_FORESEE_ONE: BaseCardId = BaseCardId(uuid!("8217b59b-6573-484b-9f3b-203e86e1d841"));
/// {Foresee(foresee)}.
pub const TEST_FORESEE_TWO: BaseCardId = BaseCardId(uuid!("89e34264-a69c-48a4-867e-add7b811394b"));
/// {Foresee(foresee)}. Draw {cards(cards)}.
pub const TEST_FORESEE_ONE_DRAW_A_CARD: BaseCardId = BaseCardId(uuid!("820faab3-37c1-46fa-a314-5f023ec739a1"));
/// Draw {cards(cards)}.  {ReclaimForCost(reclaim)}
pub const TEST_DRAW_ONE_RECLAIM: BaseCardId = BaseCardId(uuid!("0cba1386-d1b6-4f57-8ccc-d92f8be01d7c"));
/// {Foresee(foresee)}.  {ReclaimForCost(reclaim)}
pub const TEST_FORESEE_ONE_RECLAIM: BaseCardId = BaseCardId(uuid!("86ffc58b-96db-4106-a892-8ae2a70719e6"));
/// Return a card from your void to your hand.
pub const TEST_RETURN_VOID_CARD_TO_HAND: BaseCardId = BaseCardId(uuid!("46e20fe4-36ca-438d-91a6-fac880ee9495"));
/// {choose_one} {bullet} {energy(mode1_cost)}: Draw {cards(cards1)}. {bullet} {energy(mode2_cost)}: Draw {cards(cards2)}.
pub const TEST_MODAL_DRAW_ONE_OR_DRAW_TWO: BaseCardId = BaseCardId(uuid!("029889e9-25bc-438f-a492-8813febd65d8"));
/// {choose_one} {bullet} {energy(mode1_cost)}: Draw {cards(cards)}. {bullet} {energy(mode2_cost)}: {Dissolve} an enemy character.
pub const TEST_MODAL_DRAW_ONE_OR_DISSOLVE_ENEMY: BaseCardId = BaseCardId(uuid!("9847b3fc-1e7f-44e5-90af-1240ae12aaee"));
/// Return an enemy character to hand.
pub const TEST_RETURN_TO_HAND: BaseCardId = BaseCardId(uuid!("cf2f292b-f02c-4130-aff7-3f48fd147633"));
/// Gain {points(points)}.
pub const TEST_GAIN_POINTS: BaseCardId = BaseCardId(uuid!("995b52a1-b368-4c83-ae05-8ab3800ca618"));
/// Gain {energy(e)}.
pub const TEST_GAIN_ENERGY: BaseCardId = BaseCardId(uuid!("db191470-7a5b-4133-b731-8a81767d46e1"));
/// Put the {top_n_cards(to_void)} of your deck into your void.
pub const TEST_DECK_TO_VOID: BaseCardId = BaseCardId(uuid!("a7340f26-b759-458c-b8cb-b6fcc36fe412"));
/// Discard {cards(discards)}.
pub const TEST_DISCARD: BaseCardId = BaseCardId(uuid!("6e76f193-dcf0-4faf-b1f7-50af2e0dc8a2"));
/// Discard {cards(discards)}.
pub const TEST_DISCARD_TWO: BaseCardId = BaseCardId(uuid!("ef6d55f9-49ba-4637-af50-91068cb3a2b2"));
/// {Materialized} Draw {cards(cards)}.
pub const TEST_MATERIALIZED_DRAW_CARD: BaseCardId = BaseCardId(uuid!("f62670ae-73ad-4645-8de4-4cd8fb58b920"));
pub const DREAMWELL_PRODUCE_0: DreamwellCardId = DreamwellCardId(uuid!("146ae27e-a8ac-4f3c-aef2-cf2211e4bcfe"));
pub const DREAMWELL_PRODUCE_1: DreamwellCardId = DreamwellCardId(uuid!("ee7b0367-f7c3-46c3-94db-b29cfd8dc2d2"));
pub const DREAMWELL_PRODUCE_2_STARTER: DreamwellCardId = DreamwellCardId(uuid!("308fd4c0-ca98-4bfa-a9be-c29b36a145fd"));
/// {Foresee}.
pub const DREAMWELL_FORESEE: DreamwellCardId = DreamwellCardId(uuid!("40c77ea8-a021-4bc6-8970-0853c03f3fe0"));
/// Gain {points}.
pub const DREAMWELL_GAIN_POINTS: DreamwellCardId = DreamwellCardId(uuid!("d386663c-9e9f-4b8e-b410-f3467e39801b"));
/// Gain {e}.
pub const DREAMWELL_GAIN_ENERGY: DreamwellCardId = DreamwellCardId(uuid!("107c3b3f-6131-4ff8-afcb-f0ce4188848f"));
/// Draw {cards}. Discard {discards}.
pub const DREAMWELL_DRAW_DISCARD: DreamwellCardId = DreamwellCardId(uuid!("40e4381f-12f7-46b9-ae50-67b3195781b1"));
/// Put the {top_n_cards(to_void)} of your deck into your void.
pub const DREAMWELL_MILL_3: DreamwellCardId = DreamwellCardId(uuid!("a2cdf115-8e1a-455e-a118-123f6f36c7ba"));

pub const ALL_TEST_CARD_IDS: &[BaseCardId] = &[
    TEST_VANILLA_CHARACTER,
    TEST_DISSOLVE,
    TEST_COUNTERSPELL,
    TEST_COUNTERSPELL_UNLESS_PAYS,
    TEST_VARIABLE_ENERGY_DRAW,
    TEST_TRIGGER_GAIN_SPARK_ON_PLAY_CARD_ENEMY_TURN,
    TEST_FAST_MULTI_ACTIVATED_ABILITY_DRAW_CARD_CHARACTER,
    TEST_RETURN_ONE_OR_TWO_VOID_EVENT_CARDS_TO_HAND,
    TEST_MODAL_RETURN_TO_HAND_OR_DRAW_TWO,
    TEST_PREVENT_EVENT_WHICH_COULD_DISSOLVE_ALLY,
    TEST_FORESEE_ONE_DRAW_RECLAIM,
    TEST_COUNTERSPELL_CHARACTER,
    TEST_NAMED_DISSOLVE,
    TEST_DRAW_ONE,
    TEST_TRIGGER_GAIN_SPARK_WHEN_MATERIALIZE_ANOTHER_CHARACTER,
    TEST_TRIGGER_GAIN_TWO_SPARK_ON_PLAY_CARD_ENEMY_TURN,
    TEST_ACTIVATED_ABILITY_DRAW_CARD,
    TEST_MULTI_ACTIVATED_ABILITY_DRAW_CARD_CHARACTER,
    TEST_FAST_ACTIVATED_ABILITY_DRAW_CARD_CHARACTER,
    TEST_ACTIVATED_ABILITY_DISSOLVE_CHARACTER,
    TEST_DUAL_ACTIVATED_ABILITY_CHARACTER,
    TEST_FORESEE_ONE,
    TEST_FORESEE_TWO,
    TEST_FORESEE_ONE_DRAW_A_CARD,
    TEST_DRAW_ONE_RECLAIM,
    TEST_FORESEE_ONE_RECLAIM,
    TEST_RETURN_VOID_CARD_TO_HAND,
    TEST_MODAL_DRAW_ONE_OR_DRAW_TWO,
    TEST_MODAL_DRAW_ONE_OR_DISSOLVE_ENEMY,
    TEST_RETURN_TO_HAND,
    TEST_GAIN_POINTS,
    TEST_GAIN_ENERGY,
    TEST_DECK_TO_VOID,
    TEST_DISCARD,
    TEST_DISCARD_TWO,
    TEST_MATERIALIZED_DRAW_CARD,
];

pub const ALL_TEST_DREAMWELL_CARD_IDS: &[DreamwellCardId] = &[
    DREAMWELL_PRODUCE_0,
    DREAMWELL_PRODUCE_1,
    DREAMWELL_PRODUCE_2_STARTER,
    DREAMWELL_FORESEE,
    DREAMWELL_GAIN_POINTS,
    DREAMWELL_GAIN_ENERGY,
    DREAMWELL_DRAW_DISCARD,
    DREAMWELL_MILL_3,
];
