[package]
name = "display_data"
version = "0.0.0"
edition = "2021"
[lints]
workspace = true


[lib]
test = false
doctest = false
bench = false

[dependencies]
action_data = { path = "../action_data" }
ai_data = { path = "../ai_data" }
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }
masonry = { path = "../masonry" }
ui_components = { path = "../ui_components" }

bon = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
uuid = { workspace = true }