[package]
name = "display_data"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
action_data = { path = "../action_data" }
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }
masonry = { path = "../masonry" }

bon = "3"
schemars = "0.8"
serde = { version = "1", features = ["derive"] }
