[package]
name = "battle_state"
version = "0.0.0"
edition = "2024"
[lints]
workspace = true


[lib]
doctest = false
bench = false

[dependencies]
ability_data = { path = "../ability_data" }
ai_data = { path = "../ai_data" }
core_data = { path = "../core_data" }
quest_state = { path = "../quest_state" }
tabula_data = { path = "../tabula_data" }
tabula_ids = { path = "../tabula_ids" }

bit-vec = { workspace = true }
enum-iterator = { workspace = true }
enumset = { workspace = true }
rand = { workspace = true }
rand_xoshiro = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
uuid = { workspace = true }