[package]
name = "user_data"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
battle_data_old = { path = "../battle_data_old" }
core_data = { path = "../core_data" }
quest_data = { path = "../quest_data" }

schemars = "0.8"
serde = { version = "1", features = ["derive"] }