[package]
name = "user_data"
version = "0.0.0"
edition = "2024"
[lints]
workspace = true


[lib]
test = false
doctest = false
bench = false

[dependencies]
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }
quest_data = { path = "../quest_data" }

schemars = { workspace = true }
serde = { workspace = true }