[package]
name = "dev_server"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "dev_server"
path = "src/dev_server.rs"
test = false
doctest = false
bench = false

[dependencies]
client_test_scenarios = { path = "../client_test_scenarios" }
core_data = { path = "../core_data" }
display_data_old = { path = "../display_data_old" }
logging = { path = "../logging" }
plugin = { path = "../plugin" }
rules_engine_old = { path = "../rules_engine_old" }

axum = { version = "0.8", features = ["macros"] }
axum-macros = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tracing = "0.1"