[package]
name = "dev_server"
version = "0.0.0"
edition = "2021"
[lints]
workspace = true


[[bin]]
name = "dev_server"
path = "src/dev_server.rs"
test = false
doctest = false
bench = false

[dependencies]
battle_state = { path = "../battle_state" }
client_test_scenarios = { path = "../client_test_scenarios" }
core_data = { path = "../core_data" }
display_data = { path = "../display_data" }
logging = { path = "../logging" }
plugin = { path = "../plugin" }
rules_engine = { path = "../rules_engine" }
test_utils = { path = "../test_utils" }

axum = { version = "0.8", features = ["macros"] }
axum-macros = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tracing = "0.1"