[package]
name = "dev_server"
version = "0.0.0"
edition = "2024"
[lints]
workspace = true


[[bin]]
name = "dev_server"
path = "src/dev_server.rs"
test = false
doctest = false
bench = false

[dependencies]
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }
display_data = { path = "../display_data" }
logging = { path = "../logging" }
plugin = { path = "../plugin" }
rules_engine = { path = "../rules_engine" }
test_utils = { path = "../test_utils" }

axum = { workspace = true }
axum-macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }