[package]
name = "dev_server"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "dev_server"
path = "src/dev_server.rs"
test = false
doctest = false
bench = false

[dependencies]
client_test_scenarios = { path = "../client_test_scenarios" }
core_data = { path = "../core_data" }
display_data = { path = "../display_data" }
plugin = { path = "../plugin" }
rules_engine = { path = "../rules_engine" }

axum = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
