[package]
name = "client_test_scenarios"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/client_test_scenarios.rs"
test = false
doctest = false
bench = false

[dependencies]
action_data_old = { path = "../action_data_old" }
battle_data_old = { path = "../battle_data_old" }
core_data = { path = "../core_data" }
display_data_old = { path = "../display_data_old" }
masonry = { path = "../masonry" }

uuid = { version = "1", features = ["serde", "v4"] }