[package]
name = "client_test_scenarios"
version = "0.0.0"
edition = "2021"
[lints]
workspace = true


[lib]
path = "src/client_test_scenarios.rs"
test = false
doctest = false
bench = false

[dependencies]
action_data = { path = "../action_data" }
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }
display_data = { path = "../display_data" }
masonry = { path = "../masonry" }
ui_components = { path = "../ui_components" }

uuid = { workspace = true }