[package]
name = "tracing_macros"
version = "0.0.0"
edition = "2021"
[lints]
workspace = true


[lib]
doctest = false
bench = false

[dependencies]
battle_queries = { path = "../battle_queries" }
battle_state = { path = "../battle_state" }
core_data = { path = "../core_data" }
display_data = { path = "../display_data" }

chrono = "0.4"
rand_xoshiro = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = "0.27"
tracing = "0.1"
tracing-error = "0.2"
tracing-forest = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }
