[package]
name = "ai_core"
version = "0.0.0"
description = "Core data types and functions for AI system"
license = "Apache-2.0"
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
rand = "0.9"