[package]
name = "game_creation"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
battle_data = { path = "../battle_data" }
core_data = { path = "../core_data" }

uuid = { version = "1", features = ["serde"] }