[package]
name = "tabula_ids"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[lib]
test = false
doctest = false
bench = false

[dependencies]
core_data = { path = "../core_data" }
tabula_data = { path = "../tabula_data" }

uuid = { workspace = true }