[package]
name = "ai_agents"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
action_data = { path = "../action_data" }
ai_core = { path = "../ai_core" }
ai_data = { path = "../ai_data" }
ai_game_integration = { path = "../ai_game_integration" }
ai_monte_carlo = { path = "../ai_monte_carlo" }
ai_tree_search = { path = "../ai_tree_search" }
battle_data = { path = "../battle_data" }
battle_mutations = { path = "../battle_mutations" }
battle_queries = { path = "../battle_queries" }
core_data = { path = "../core_data" }

rand = "0.9"