languages:
- rust
- typescript

encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths: []

read_only: false

excluded_tools: []

initial_prompt: ""

project_name: "dreamtides"
included_optional_tools: []
