[package]
name = "core_data"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
derive_more = { version = "1.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }