[package]
name = "parser"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
core_data = { path = "../core_data" }
ability_data = { path = "../ability_data" }

chumsky = "0.9"